-- Basis-Tabelle News (Internes / Mitglieder-News)
-- Voraussetzung: public.members, Hilfsfunktionen is_vorstand(), is_member(),
-- get_auth_member_id(), set_content_created_by() (RUNBOOK Schritte 1–8).
-- Danach optional: supabase-feedback-cascade-delete.sql (News-Trigger),
-- supabase-media-storage-paths.sql (Spalte image_storage_path — hier enthalten).
-- Siehe docs/supabase/RUNBOOK.md

-- ---------------------------------------------------------------------------
-- Tabelle
-- ---------------------------------------------------------------------------

create table if not exists public."News" (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text,
  excerpt text,
  content text,
  published boolean not null default true,
  sichtbarkeit text not null default 'draft',
  image text,
  image_storage_path text,
  created_by bigint references public.members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public."News" is
  'News / Internes — sichtbarkeit: public | members | draft';

comment on column public."News".sichtbarkeit is
  'public = alle; members = nur Vereinsmitglieder; draft = nur Vorstand';

comment on column public."News".published is
  'Legacy-Flag; parallel zu sichtbarkeit; Admin setzt bei Veröffentlichung';

comment on column public."News".image_storage_path is
  'Relativer Pfad im Bucket media, z. B. shared/images/news-header.jpg';

comment on column public."News".created_by is
  'Mitglied/Vorstand, das den Beitrag angelegt hat.';

create unique index if not exists news_slug_key
  on public."News" (slug)
  where slug is not null;

create index if not exists news_created_by_idx
  on public."News" (created_by);

create index if not exists news_created_at_idx
  on public."News" (created_at desc);

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

alter table public."News" enable row level security;

drop policy if exists "Public News lesen" on public."News";
drop policy if exists news_select_anon on public."News";
drop policy if exists news_select_authenticated on public."News";
drop policy if exists "Authenticated full access News" on public."News";
drop policy if exists news_insert_vorstand on public."News";
drop policy if exists news_update_vorstand on public."News";
drop policy if exists news_delete_vorstand on public."News";
drop policy if exists news_insert_member_draft on public."News";
drop policy if exists news_update_member_draft on public."News";
drop policy if exists news_delete_member_draft on public."News";

create policy news_select_anon
  on public."News"
  for select
  to anon
  using (sichtbarkeit = 'public');

create policy news_select_authenticated
  on public."News"
  for select
  to authenticated
  using (
    public.is_vorstand()
    or sichtbarkeit = 'public'
    or (
      sichtbarkeit = 'members'
      and public.is_member()
    )
    or created_by = public.get_auth_member_id()
  );

create policy news_insert_vorstand
  on public."News"
  for insert
  to authenticated
  with check (public.is_vorstand());

create policy news_update_vorstand
  on public."News"
  for update
  to authenticated
  using (public.is_vorstand())
  with check (public.is_vorstand());

create policy news_delete_vorstand
  on public."News"
  for delete
  to authenticated
  using (public.is_vorstand());

-- ---------------------------------------------------------------------------
-- Trigger: created_by
-- ---------------------------------------------------------------------------

drop trigger if exists news_set_created_by on public."News";

create trigger news_set_created_by
  before insert on public."News"
  for each row
  execute function public.set_content_created_by();

-- ---------------------------------------------------------------------------
-- Trigger: Feedback-Module bei Löschung (optional, falls feedback vorhanden)
-- ---------------------------------------------------------------------------

create or replace function public.delete_feedback_modules_for_news()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.feedback_modules
  where entity_type = 'news'
    and entity_id = old.id;

  return old;
end;
$$;

drop trigger if exists news_delete_feedback_modules on public."News";

create trigger news_delete_feedback_modules
  before delete on public."News"
  for each row
  execute function public.delete_feedback_modules_for_news();

-- ---------------------------------------------------------------------------
-- API-Zugriff (wie Termine)
-- ---------------------------------------------------------------------------

grant select on public."News" to anon, authenticated;
grant insert, update, delete on public."News" to authenticated;
